#ifndef SENSORSUNLEASHED_GLOBAL_H
#define SENSORSUNLEASHED_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SENSORSUNLEASHED_LIBRARY)
#  define SENSORSUNLEASHEDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SENSORSUNLEASHEDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SENSORSUNLEASHED_GLOBAL_H
